apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rider-service-hpa
  namespace: lastmile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rider-deployment
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
